# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
inhibit_all_warnings!

target 'MovieSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieSearchApp
  pod 'Bond', '~> 7.6.6'


end
